version: '2'
services:
  ios-mkdocs:
    image: squidfunk/mkdocs-material:4.6.0
    container_name: ios-mkdocs
    ports:
      - "8000:8000"
    volumes:
      - ./:/docs
    tty: true
    environment:
      - GITHUB_ACTIONS=$GITHUB_ACTIONS
    entrypoint: /bin/sh /docs/entrypoint.sh