site_name: "adstir Integration Guide for iOS"
theme:
  name: 'material'
  language: 'ja'
  palette:
    primary: 'white'
    accent: 'white'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: true
  custom_dir: 'custom_dir'
  logo: 'images/adstir_icon.ico'

use_directory_urls: false

extra:
  language: 'jp'
  config:
    version:
      adstir: 2.14.7
      adcolony: 4.1.2
      adcorsa: 2.1.0
      applovin: 6.10.1
      facebook: 5.6.0
      imobile: 2.0.20
      maio: 1.5.1
      mobvista: 10.1.71
      mopub: 5.10.0
      nend: 5.3.0
      tapjoy: 12.3.4
      tiktok: 2.4.6.7
      unityads: 3.3.0
      zucks: 4.6.1
      facebook: 5.6.0
    sample_url: 'https://dl.ad-stir.com/sample/AdstirAdsSdkiOS-2.14.6-SampleApp.zip'

# CSSの設定
extra_css:
  - css/custom.css

# 拡張機能の設定
markdown_extensions:
  - admonition # 警告文出せるやつ
  - footnotes
  - pymdownx.superfences
  - codehilite:
      linenums: false
  - meta
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: true
      anchorlink: true
  - pymdownx.tasklist:  
      custom_checkbox: true
  - pymdownx.details

nav:
  - スタートガイド: index.md
  - adstir: 
      - はじめに: adstir/index.md
      - 初期設定: 
        - SDKの組み込み:
          - CocoaPods: adstir/init/cocoapods.md
          - 手動組み込み: adstir/init/manual_integration.md
      - 対応ネットワーク: 
        - 対応ネットワーク一覧: adstir/network/index.md
        - AdColony: adstir/network/adcolony.md
        - AdCorsa: adstir/network/adcorsa.md
        - AppLovin: adstir/network/applovin.md
        - imobile: adstir/network/imobile.md
        - maio: adstir/network/maio.md
        - Mobvista: adstir/network/mobvista.md
        - MoPub: adstir/network/mopub.md
        - nend: adstir/network/nend.md
        - TapJoy: adstir/network/tapjoy.md
        - TikTok: adstir/network/tiktok.md
        - UnityAds: adstir/network/unityads.md
        - Zucks: adstir/network/zucks.md

      - 広告の実装:
        - バナー: adstir/ad/banner.md
        - スワイプインタースティシャル: adstir/ad/swipe.md
        - ネイティブ: 
          - ネイティブライクバナー: adstir/ad/native/native_banner.md
          - フルカスタマイズ: adstir/ad/native/custom.md
          - ネイティブ動画: adstir/ad/native/native_video.md
        - 動画リワード: 
          - 実装: adstir/ad/vr/index.md
          - リワードコールバック: adstir/ad/vr/callback.md
        - 全画面インタースティシャル: adstir/ad/interstitial.md
      - APIリファレンス: 
        - 一覧: adstir/api/index.md
        - バナー:
          - AdstirMraidView: adstir/api/banner/AdstirMraidView-Class-Reference.md
          - AdstirMraidViewDelegate: adstir/api/banner/AdstirMraidViewDelegate-Protocol-Reference.md
        - スワイプインタースティシャル:
          - AdstirFullscreenView: adstir/api/swipe/AdstirFullscreenView-Class-Reference.md
        - ネイティブ:
          - AdstirNativeAd: adstir/api/native/AdstirNativeAd-Class-Reference.md
          - AdstirNativeAdDelegate: adstir/api/native/AdstirNativeAdDelegate-Protocol-Reference.md
          - AdstirNativeAdResponse: adstir/api/native/AdstirNativeAdResponse-Class-Reference.md
          - AdstirLoadImageDeledate: adstir/api/native/AdstirLoadImageDeledate-Protocol-Reference.md
          - AdstirLoadSmallImageDeledate: adstir/api/native/AdstirLoadSmallImageDeledate-Protocol-Reference.md
          - ネイティブ動画:
            - AdstirNativeVideoAd: adstir/api/native/video/AdstirNativeVideoAd-Class-Reference.md
            - AdstirNativeVideoView: adstir/api/native/video/AdstirNativeVideoView-Class-Reference.md
            - AdstirNativeVideoViewDelegate: adstir/api/native/video/AdstirNativeVideoViewDelegate-Protocol-Reference.md
        - 動画リワード/全画面インタースティシャルの初期化:
          - AdstirVideoAds: adstir/api/AdstirVideoAds-Class-Reference.md
        - 動画リワード:
          - AdstirVideoReward: adstir/api/video/AdstirVideoReward-Class-Reference.md
          - AdstirVideoRewardDelegate: adstir/api/video/AdstirVideoRewardDelegate-Protocol-Reference.md
        - 全画面インタースティシャル:
          - AdstirInterstitial: adstir/api/interstitial/AdstirInterstitial-Class-Reference.md
          - AdstirInterstitialDelegate: adstir/api/interstitial/AdstirInterstitialDelegate-Protocol-Reference.md
      - その他:
          - ユーザデータアクセス許可に関して: adstir/info/user_data.md 
          - よくある質問: adstir/info/question.md
  - AdMob: 
      - はじめに: admob/index.md
      - AdMobメディエーション: admob/network.md
      - よくある質問: admob/question.md
  - APS:
      - APSの初期設定: aps/init.md
      - AdMobバナー: aps/banner.md
      - AdMobインタースティシャル: aps/interstitial.md
  - 変更履歴: changelog.md

plugins:
  - search
  - markdownextradata: {}
